### ISSUE TITLE
plungin funktioniert nicht mehr.

### ISSUE THREAD

**Issue by Basti77** [fhem/INDEGO#1]
auch mit der letzten Version kann man den Bot nicht mehr steuern.

last_error | read from https://api.indego.iot.bosch-si.com:443 timed out

nur der State wird richtig übermittelt. 

ist das ein Bekanntes Problem?

INDEGO 350+
ich glaube das Problem fing nach dem letzten FW update an. sollte man lieber ein downgrade machen, oder liegt es an der Bosh api bzw clowd?

**Comment by Basti77** [comment]
![image](https://user-images.githubusercontent.com/8112783/118397751-dcee1d00-b655-11eb-82c0-41e826ae657a.png)

Hier sieht man ein Ausschnitt aus dem Log der FW.
die Kommunikation zwischen den Geräten und der Wolke steht.

**Comment by vuffiraa72** [comment]
Die Fehlermeldung sehe ich bei mir gerade auch, vorher wurden aber aktuelle Werte abgerufen. Du kannst es immer mit den Verhalten in der App vergleichen. Wenn es sich dort ähnlich verhält, liegt es an den Servern. Die Kommunikation wurde in letzter Zeit nicht verändert. Welche Version benutzt du bei dir? (Master oder Dev)

Wenn es nur in FHEM nicht funktioniert, bitte ein Log mit verbose=5 aufzeichnen.

**Comment by Basti77** [comment]
dank für Deine schnelle Antwort.
Master, aber ich sehe gerade das die App (Android auch suckt)
Auch dort sehe ich nur den Status. Keine Befehle möglich. also liegts an Bosch...
interessant ist das auch eine Webcam (Reolink) genau mit der selben IP wie der der Bot hin und her funkt. 192.168.200.241
214 ist der Bot 238 das Handy.

**Comment by vuffiraa72** [comment]
Sonntags ist doch ein guter Zeitpunkt für ein Serverupdate, da dürfen die Indegos eh nicht raus und Krach machen. Du kannst ja noch mal Rückmeldung geben, ob sich das Problem bis morgen wieder gelöst hast. Ansonsten, wie oben geschrieben, FHEM-Log aufzeichnen.

**Comment by Basti77** [comment]
also ich bekommen keine Verbindung zum bot mit der APP oder über das Plugin.

wie lange muss das log den laufen?
021.05.18 19:12:01 5 : INDEGO igor: called function GetStatus()
2021.05.18 19:12:01 4 : INDEGO igor: Read password from file
2021.05.18 19:12:01 5 : INDEGO igor: called function SendCommand()
2021.05.18 19:12:01 4 : INDEGO igor: REQ state
2021.05.18 19:12:01 5 : INDEGO igor: GET https://api.indego.iot.bosch-si.com/api/v1/alms/904600916/state
2021.05.18 19:12:01 5 : INDEGO igor: header x-im-context-id: 83815689-3247-42f3-8be7-1eaaa009db4a

2021.05.18 19:12:01 5 : INDEGO igor: called function ReceiveCommand() rc: HASH(0x5a817a0) err: data: { "state" : 258, "map_update_available" : false, "mowed" : 97, "mowmode" : 3, "xPos" : 52, "yPos" : 137, "runtime" : { "total" : { "operate" : 48621, "charge" : 12638 }, "session" : { "operate" : 0, "charge" : 0 } }, "mapsvgcache_ts" : 1621357930826, "svg_xPos" : 1120, "svg_yPos" : 456, "config_change" : false, "mow_trig" : false }
2021.05.18 19:12:01 4 : INDEGO igor: RCV state
2021.05.18 19:12:01 4 : INDEGO igor: RES state - { "state" : 258, "map_update_available" : false, "mowed" : 97, "mowmode" : 3, "xPos" : 52, "yPos" : 137, "runtime" : { "total" : { "operate" : 48621, "charge" : 12638 }, "session" : { "operate" : 0, "charge" : 0 } }, "mapsvgcache_ts" : 1621357930826, "svg_xPos" : 1120, "svg_yPos" : 456, "config_change" : false, "mow_trig" : false }
2021.05.18 19:12:01 5 : INDEGO igor: called function Set()
2021.05.18 19:12:01 5 : INDEGO igor: called function Set()

2021.05.18 19:12:01 4 : INDEGO igor: Request GET state (longPoll)
2021.05.18 19:12:01 4 : INDEGO igor: Read password from file
2021.05.18 19:12:01 5 : INDEGO igor: called function SendCommand()
2021.05.18 19:12:01 4 : INDEGO igor: REQ longpollState
2021.05.18 19:12:01 5 : INDEGO igor: GET https://api.indego.iot.bosch-si.com/api/v1/alms/904600916/state?longpoll=true&timeout=3600&last=258
2021.05.18 19:12:01 5 : INDEGO igor: header x-im-context-id: 83815689-3247-42f3-8be7-1eaaa009db4a
2021.05.18 19:12:01 4 : INDEGO igor: Read password from file
2021.05.18 19:12:01 5 : INDEGO igor: called function SendCommand()
2021.05.18 19:12:01 4 : INDEGO igor: REQ alerts
2021.05.18 19:12:01 4 : INDEGO igor: successors 0: location, 1: predictive, 2: predictive/nextcutting, 3: predictive/useradjustment, 4: predictive/useradjustment?withProposal=true,
2021.05.18 19:12:01 5 : INDEGO igor: GET https://api.indego.iot.bosch-si.com/api/v1/alerts
2021.05.18 19:12:01 5 : INDEGO igor: header x-im-context-id: 83815689-3247-42f3-8be7-1eaaa009db4a
2021.05.18 19:12:02 5 : INDEGO igor: called function ReceiveCommand() rc: HASH(0x59813d0) err:  data: [ ] 
2021.05.18 19:12:02 4 : INDEGO igor: RCV alerts
2021.05.18 19:12:02 4 : INDEGO igor: RES alerts - [ ]
2021.05.18 19:12:02 4 : INDEGO igor: Read password from file
2021.05.18 19:12:02 5 : INDEGO igor: called function SendCommand()
2021.05.18 19:12:02 4 : INDEGO igor: REQ location
2021.05.18 19:12:02 4 : INDEGO igor: successors 0: predictive, 1: predictive/nextcutting, 2: predictive/useradjustment, 3: predictive/useradjustment?withProposal=true,
2021.05.18 19:12:02 5 : INDEGO igor: GET https://api.indego.iot.bosch-si.com/api/v1/alms/904600916/location
2021.05.18 19:12:02 5 : INDEGO igor: header x-im-context-id: 83815689-3247-42f3-8be7-1eaaa009db4a
2021.05.18 19:12:02 5 : INDEGO igor: called function ReceiveCommand() rc: HASH(0x5a7b6c8) err: data: { "latitude" : XX.7643, "longitude" : XX.3171 }
2021.05.18 19:12:02 4 : INDEGO igor: RCV location
2021.05.18 19:12:02 4 : INDEGO igor: RES location - { "latitude" : XX.7643, "longitude" : XX.3171 }
2021.05.18 19:12:02 4 : INDEGO igor: Read password from file
2021.05.18 19:12:02 5 : INDEGO igor: called function SendCommand()
2021.05.18 19:12:02 4 : INDEGO igor: REQ predictive
2021.05.18 19:12:02 4 : INDEGO igor: successors 0: predictive/nextcutting, 1: predictive/useradjustment, 2: predictive/useradjustment?withProposal=true,
2021.05.18 19:12:02 5 : INDEGO igor: GET https://api.indego.iot.bosch-si.com/api/v1/alms/904600916/predictive
2021.05.18 19:12:02 5 : INDEGO igor: header x-im-context-id: 83815689-3247-42f3-8be7-1eaaa009db4a
2021.05.18 19:12:02 5 : INDEGO igor: called function ReceiveCommand() rc: HASH(0x5a6ac58) err: data: { "enabled" : false }
2021.05.18 19:12:02 4 : INDEGO igor: RCV predictive
2021.05.18 19:12:02 4 : INDEGO igor: RES predictive - { "enabled" : false }
2021.05.18 19:12:02 4 : INDEGO igor: Read password from file
2021.05.18 19:12:02 5 : INDEGO igor: called function SendCommand()
2021.05.18 19:12:02 4 : INDEGO igor: REQ predictive/nextcutting
2021.05.18 19:12:02 4 : INDEGO igor: successors 0: predictive/useradjustment, 1: predictive/useradjustment?withProposal=true,
2021.05.18 19:12:02 5 : INDEGO igor: GET https://api.indego.iot.bosch-si.com/api/v1/alms/904600916/predictive/nextcutting
2021.05.18 19:12:02 5 : INDEGO igor: header x-im-context-id: 83815689-3247-42f3-8be7-1eaaa009db4a

2021.05.18 19:12:02 5 : INDEGO igor: called function ReceiveCommand() rc: HASH(0x5cb4688) err: data: { "mow_next" : "2021-05-19T11:00:00+02:00" }
2021.05.18 19:12:02 4 : INDEGO igor: RCV predictive/nextcutting
2021.05.18 19:12:02 4 : INDEGO igor: RES predictive/nextcutting - { "mow_next" : "2021-05-19T11:00:00+02:00" }
2021.05.18 19:12:02 4 : INDEGO igor: Read password from file
2021.05.18 19:12:02 5 : INDEGO igor: called function SendCommand()
2021.05.18 19:12:02 4 : INDEGO igor: REQ predictive/useradjustment
2021.05.18 19:12:02 4 : INDEGO igor: successors 0: predictive/useradjustment?withProposal=true,
2021.05.18 19:12:02 5 : INDEGO igor: GET https://api.indego.iot.bosch-si.com/api/v1/alms/904600916/predictive/useradjustment
2021.05.18 19:12:02 5 : INDEGO igor: header x-im-context-id: 83815689-3247-42f3-8be7-1eaaa009db4a
2021.05.18 19:12:02 5 : INDEGO igor: called function ReceiveCommand() rc: HASH(0x5c48180) err: data: { "user_adjustment" : 0 }
2021.05.18 19:12:02 4 : INDEGO igor: RCV predictive/useradjustment
2021.05.18 19:12:02 4 : INDEGO igor: RES predictive/useradjustment - { "user_adjustment" : 0 }
2021.05.18 19:12:02 4 : INDEGO igor: Read password from file
2021.05.18 19:12:02 5 : INDEGO igor: called function SendCommand()
2021.05.18 19:12:02 4 : INDEGO igor: REQ predictive/useradjustment?withProposal=true
2021.05.18 19:12:02 5 : INDEGO igor: GET https://api.indego.iot.bosch-si.com/api/v1/alms/904600916/predictive/useradjustment?withProposal=true
2021.05.18 19:12:02 5 : INDEGO igor: header x-im-context-id: 83815689-3247-42f3-8be7-1eaaa009db4a
2021.05.18 19:12:02 5 : INDEGO igor: called function ReceiveCommand() rc: HASH(0x5b18a88) err: data: { "user_adjustment" : 0 }
2021.05.18 19:12:02 4 : INDEGO igor: RCV predictive/useradjustment?withProposal=true
2021.05.18 19:12:02 4 : INDEGO igor: RES predictive/useradjustment?withProposal=true - { "user_adjustment" : 0 }

**Comment by vuffiraa72** [comment]
Das Log sieht soweit gut aus. Das Plugin kann Daten empfangen.
Kannst du mal loggen, wenn du versuchst 'igor' zu steuern?

**Comment by Basti77** [comment]
Über fhem:

2021-05-18 20:24:41 INDEGO igor Set_Mowing
2021.05.18 20:24:41 5 : INDEGO igor: called function Set()
2021.05.18 20:25:11 5 : INDEGO igor: called function ReceiveCommand() rc: HASH(0x5c77288) err: read from https://api.indego.iot.bosch-si.com:443 timed out data:  
2021.05.18 20:25:11 4 : INDEGO igor:state/mow RCV read from https://api.indego.iot.bosch-si.com:443 timed out
2021.05.18 20:25:11 5 : INDEGO igor: called function Set()
2021-05-18 20:25:11 INDEGO igor last_error: read from https://api.indego.iot.bosch-si.com:443 timed out
2021.05.18 20:25:11 5 : INDEGO igor: called function Set()

in den FW Log sehe ich keien verbindung zum Igor was zeitlich passen könnte.

alles sehr eigenartig.

ggf. mal ein Werksreset machen!?

**Comment by vuffiraa72** [comment]
Scheint wirklich eher ein Problem zwischen Server und Indego zu sein. Die Daten können ja vom Server abgerufen werden, aber 'Igor' scheint nicht zu antworten.
Du kannst natürlich mal das Übliche probieren, ausschalten und anschalten ;-)
Beim Werksreset weiß ich dann nicht, welche Einstellungen du dir dann vorher merken solltest.

**Comment by Basti77** [comment]
ich hab vorher noch mal etwas anders probiert. den Akku Leer werden lassen. 
der Schalter sorgt wohl für kein rechten Reset. 
ich danke dir auf jedenfalls für deine Zeit und für dies schöne Plugin!
